# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=15)),
                ('resume', models.CharField(max_length=200)),
                ('promotion', models.TextField(default='Being Shilpified!!')),
            ],
        ),
    ]
