# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '003_reguser'),
        ('website', '0002_pptuser'),
    ]

    operations = [
    ]
