# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('teamleader', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('mob_no', models.CharField(max_length=15)),
                ('radio',models.CharField(max_length=15)),
                ('tmem1',models.CharField(max_length=100)),
                ('email1',models.CharField(max_length=100)),
                ('mob1',models.CharField(max_length=15)),
                ('tmem2',models.CharField(max_length=100)),
                ('email2',models.CharField(max_length=100)),
                ('mob2',models.CharField(max_length=100)),
                ('tmem3',models.CharField(max_length=100)),
                ('email3',models.CharField(max_length=100)),
                ('mob3',models.CharField(max_length=100)),
                ('tmem4',models.CharField(max_length=100)),
                ('email4',models.CharField(max_length=100)),
                ('mob4',models.CharField(max_length=100)),
                ('tmem5',models.CharField(max_length=100)),
                ('email5',models.CharField(max_length=100)),
                ('mob5',models.CharField(max_length=100)),
                ('query',models.CharField(max_length=100))

            ],
        ),
    ]
