# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quriosity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False, verbose_name='resolved')),
            ],
            options={
                'verbose_name': 'Help Question',
                'verbose_name_plural': 'Help Questions',
            },
        ),
    ]
