# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quriosity', '0004_auto_20160905_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='responses',
            field=models.ManyToManyField(to='quriosity.Response'),
        ),
    ]
