# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quriosity', '0005_auto_20160907_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='responses',
        ),
        migrations.AddField(
            model_name='response',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quriosity.Team'),
            preserve_default=False,
        ),
    ]
