# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quriosity', '0006_auto_20160907_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='college',
            field=models.CharField(default='', max_length=50, verbose_name='college'),
        ),
        migrations.AddField(
            model_name='quser',
            name='gender',
            field=models.CharField(default='M', max_length=5, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='quser',
            name='year',
            field=models.CharField(default='', max_length=5, verbose_name='year'),
        ),
    ]
