# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quriosity', '0007_auto_20160908_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quser',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='college'),
        ),
        migrations.AlterField(
            model_name='quser',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='quser',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='year'),
        ),
    ]
