# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quriosity', '0008_auto_20160908_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='response1',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response10',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response11',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response12',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response13',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response14',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response15',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response2',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response3',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response4',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response5',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response6',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response7',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response8',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='team',
            name='response9',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
